/**
 * 📊 LIFE Evidence & Reporting Exporter
 * Resolves Issue #16 (P0.7 — LIFE Evidence & Reporting Exporter)
 */
const crypto = require('crypto');

class LifeEvidenceExporter {
    constructor(config = {}) {
        this.formulaVersion = config.formulaVersion || 'v1.2.0-mrv';
        this.stationId = config.stationId || 'MYZUBSTER_STATION_ALPHA';
    }

    /**
     * Builds the authoritative JSON Evidence Package with strict 4-tier isolation.
     */
    buildEvidencePackage(input) {
        if (!input || !input.observedFacts || !input.calculatedIndicators) {
            throw new Error('Input must provide observedFacts and calculatedIndicators');
        }

        const metadata = {
            pilotId: input.pilotId || 'PILOT_DEFAULT',
            period: input.period || { start: '2026-08-01T00:00:00Z', end: '2026-08-31T23:59:59Z' },
            formulaVersion: this.formulaVersion,
            datasetType: input.datasetType || 'SYNTHETIC', // SYNTHETIC | PILOT | VALIDATED
            qaQcStatus: input.qaQcStatus || 'QA_PASSED',
            exportedAt: new Date().toISOString()
        };

        // Tier 1: Observed Empirical Facts (Immutable)
        const observedFacts = input.observedFacts.map(fact => ({
            sensorId: fact.sensorId,
            timestamp: fact.timestamp,
            metric: fact.metric,
            value: fact.value,
            unit: fact.unit,
            rawProofHash: fact.rawProofHash || crypto.createHash('sha256').update(JSON.stringify(fact)).digest('hex')
        }));

        // Tier 2: Calculated Indicators (Deterministic)
        const calculatedIndicators = Object.entries(input.calculatedIndicators).map(([kpiName, data]) => ({
            kpiName,
            value: data.value,
            unit: data.unit,
            formula: data.formula || 'STANDARD_DELTA_CALC',
            evidenceRefs: observedFacts.map(f => f.rawProofHash).slice(0, 3) // Linked provenance
        }));

        // Tier 3: Agent-Generated Interpretation (Non-empirical narrative)
        const agentInterpretation = {
            isEmpiricalObservation: false, // Critical acceptance criteria
            analystAgent: input.agentInterpretation?.agentName || 'Zorgax-Analyst-v1',
            narrative: input.agentInterpretation?.text || 'Standard automated telemetry interpretation.',
            confidenceScore: input.agentInterpretation?.confidence || 0.95
        };

        // Tier 4: Governance & Validation Status
        const validationStatus = {
            state: input.validationStatus || 'PEER_REVIEW_READY',
            certifiedBy: input.certifiedBy || 'STATION_SCIENTIFIC_COUNCIL',
            signatures: input.signatures || []
        };

        const pkg = {
            packageId: `LIFE_EVD_${metadata.pilotId}_${Date.now()}`,
            metadata,
            observedFacts,
            calculatedIndicators,
            agentInterpretation,
            validationStatus
        };

        pkg.packageSignature = crypto.createHash('sha256').update(JSON.stringify(pkg)).digest('hex');
        return pkg;
    }

    /**
     * Exports KPIs to RFC-4180 compliant CSV format.
     */
    exportToCsv(evidencePackage) {
        const rows = [
            ['KPI_Name', 'Value', 'Unit', 'Formula_Version', 'Dataset_Type', 'QA_QC_Status']
        ];

        for (const kpi of evidencePackage.calculatedIndicators) {
            rows.push([
                `"${kpi.kpiName}"`,
                kpi.value,
                `"${kpi.unit}"`,
                `"${evidencePackage.metadata.formulaVersion}"`,
                `"${evidencePackage.metadata.datasetType}"`,
                `"${evidencePackage.metadata.qaQcStatus}"`
            ]);
        }

        return rows.map(r => r.join(',')).join('\n');
    }

    /**
     * Exports human-readable Markdown summary.
     */
    exportHumanReadableSummary(evidencePackage) {
        const meta = evidencePackage.metadata;
        const indicators = evidencePackage.calculatedIndicators.map(k => 
            `- **${k.kpiName}**: ${k.value} ${k.unit} *(Formula: ${k.formula})*`
        ).join('\n');

        return `# 🌊 LIFE MRV Scientific Evidence Report
**Package ID**: \`${evidencePackage.packageId}\`  
**Pilot**: ${meta.pilotId} | **Status**: ${meta.datasetType} (${meta.qaQcStatus})  
**Formula Version**: \`${meta.formulaVersion}\` | **Signature**: \`${evidencePackage.packageSignature}\`

---

## 📈 Calculated Environmental Indicators
${indicators}

---

## 🤖 Agent Qualitative Assessment
> ⚠️ *Notice: Qualitative interpretations are generated by AI software entities and are strictly isolated from empirical sensor measurements.*

* **Analyst Entity**: ${evidencePackage.agentInterpretation.analystAgent}
* **Assessment**: ${evidencePackage.agentInterpretation.narrative}
* **Confidence**: ${(evidencePackage.agentInterpretation.confidenceScore * 100).toFixed(1)}%

---
*Signed-off by MyZubster Space Station LIFE Scientific Exporter.*
`;
    }
}

module.exports = {
    LifeEvidenceExporter
};
